### ISSUE TITLE
Build new how it works iphone carousel

### ISSUE THREAD

**Issue by pjatx** [Corona-Trace/coronatrace.org#28]
- [x] Build
- [x] Integrate with CMS

**Comment by pjatx** [comment]
![how it works](https://user-images.githubusercontent.com/5004634/78577844-4d403300-77f4-11ea-8e58-04fd2cb7e41b.jpg)

**Comment by pjatx** [comment]
Deploy Preview: https://5e8b51c40021120006ea28c2--pensive-pike-fa3f5a.netlify.com/

**Comment by pjatx** [comment]
@LauraFaustman lmk when you have a chance to take a look at this! can push it out whenever

**Comment by LauraFaustman** [comment]
For the sake of consistency, I changed "coronavirus" to "COVID-19" in the hero (did in Contentful and hit publish, let me know if I should have done differently). We should be consistent about the name of our enemy :)

Also question - the carousel of content explaining how it works is advancing automatically, is that by design or a factor of the preview? There's so much to absorb there with the animated screenshot, it's hard to know where to look. I think mirroring the layout of the section below would be more successful in terms of ingesting the content.  How hard would it be to have this section visually match the "Getting Started" Section, with a clear section title and the four icons w/ descriptions? Happy to help come up with iconography if that's an option. If this design has already been blessed than let me know, I might re-approach the copy.....

**Comment by pjatx** [comment]
@LauraFaustman 

So I think currently, it says "coronavirus" everywhere on the site. Maybe we should change all the other references as well? 

It's by default, but we can turn it off or slow it down. Oh man - I had already gotten approval for that design on slack and spent a bunch of hours coding it : ( Do you not think it works? I think it helps the user understand what the experience will be like more than a bunch of static content. 

Reminder the old how it works section got renamed to "Getting Started" and will still remain below.

**Comment by LauraFaustman** [comment]
If you've already gotten approval for it then don't sweat it, ignore me!

Ah, I see - in the app, it's COVID-19 pretty much everywhere (fits more easily into microcopy) and a lot of the revisions I made in the doc for website revisions were shifting to COVID-19.... I think we need to come to a consensus on that like.... now.... stay tuned on that!

**Comment by pjatx** [comment]
@LauraFaustman ok! Is all the existing copy in the carousels ok before I press go?

**Comment by LauraFaustman** [comment]
I think we're good as long as we slow down the carousel a bit, it's advancing to fast to ready the content fully! Fire away.
